In [ ]:
# This is a comment

# R
# Learning a new language 

#1. Data types
#2. Operators 
#3. Control structure - Logic
#4. Control structure - Loops
#5. Functions


In [2]:
#Data types

# Basic data types (scalars)
# Numerical
# Character 
# Logical



In [6]:
# Numerical data
class(1) 

[1] "numeric"

In [7]:
class(1.0)

[1] "numeric"

In [8]:
class(-1)

[1] "numeric"

In [4]:
class(1e+3)

[1] "numeric"

In [12]:
# Character (Categorical)
class('Hello')

[1] "character"

In [13]:
class("Wow")

[1] "character"

In [14]:
class("1")

[1] "character"

In [22]:
# Logical (True, False and Missing)
#True
print(class(TRUE))


[1] "logical"


In [24]:
#False
print(class(FALSE))


[1] "logical"


In [25]:
#True
class(T)

[1] "logical"

In [26]:
#False
class(F)

[1] "logical"

In [27]:
#Missing
class(NA)

[1] "logical"

In [ ]:
# Collections
# Vectors
# These are type specific
# to write a vector which is a collection you start with the c() function
# Vectors are one dimensional with length as their only dimension

#Numeric vector
print(class(c(1, 4, 2, 6, 7, 9, 0)))


[1] "numeric"


In [35]:
#Character vector

class(c('Monday', 'Wednesday', 'Friday'))

[1] "character"

In [36]:
# Logical vector

class(c(T, F, F, T, T))

[1] "logical"

In [37]:
#Vectors can be of one and one type only. If you mix then they will transform to a single type. 
# The precedence being character > numeric > logical

c('Hello', 4)

[1] "Hello" "4"    

In [ ]:
#characrer of logical
c('Hello', F)

[1] "Hello" "FALSE"

In [ ]:
#character over numeric and logical
c(F, 'Hi', 56)

[1] "FALSE" "Hi"    "56"   

In [ ]:
#numeric over logical
c(45, F)

[1] 45  0

In [ ]:
#numeric over logical
c(33, T)

[1] 33  1

In [ ]:
#numeric over logical
c(F, T, 18)

[1]  0  1 18

In [45]:
# length of a vector

print(length(c(3, 6, 1, 8, 9, 2, 4, 5, 7, 2, 8)))


[1] 11


In [46]:
length(c('yam', 'beans', 'rice'))

[1] 3

In [ ]:
# Matrices (these have two dimension being rows and columns)
#like vectors matrices can be of only one type
matrix(c(5, 3, 6, 1, 8, 2, 7, 7, 4, 3, 6, 1, 8, 9, 3, 2, 5, 6, 7, 8, 9, 3, 2, 2), nrow=4)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    5    8    4    8    5    9
[2,]    3    2    3    9    6    3
[3,]    6    7    6    3    7    2
[4,]    1    7    1    2    8    2

In [38]:
# Lists

list(name='Lara', location='UK', children=c('Taiwo', 'Kehinde'), childrens_ages=c(3,3), knows_data=T)

$name
[1] "Lara"

$location
[1] "UK"

$children
[1] "Taiwo"   "Kehinde"

$childrens_ages
[1] 3 3

$knows_data
[1] TRUE


In [57]:
# Dataframe
# Spreadsheet
# usually when you import ata it will come in as a dataframe

In [59]:
############
# OPERATORS
############

#symbols that have some kind of value like functions

In [60]:
# Assignment operators
# =, <-, ->
#These assign a value (which is a datatype) to a named entity called a variable

In [1]:
scores = c(98, 82, 93, 97, 91, 94, 94, 96, 92, 91, 91, 90)

In [7]:
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [66]:
class(scores)

[1] "numeric"

In [67]:
length(scores)

[1] 12

In [2]:
fruits <- c('Mango', 'Guava', 'Cashew', 'Agbalumo')

In [70]:
length(fruits)

[1] 4

In [3]:
c(T, T, T, F, F) -> something

In [9]:
something

[1]  TRUE  TRUE  TRUE FALSE FALSE

In [73]:
# Mathematical operators 
# + - * / %% ^ 

In [4]:
x <- 3
y <- 2

In [75]:
x + y

[1] 5

In [76]:
x - y

[1] 1

In [77]:
x * y

[1] 6

In [78]:
x / y

[1] 1.5

In [ ]:
#modulus for getting remainder
x %% y

[1] 1

In [ ]:
#exponent (power)
x ^ y

[1] 9

In [ ]:
#square root
16 ^ 0.5

[1] 4

In [ ]:
# Comparison operators 
#  ==, !=, >, <, >=, <=, %in%, !
# comparison operators retun a logal (boolean ie True or false)

x == y

[1] FALSE

In [84]:
x != y

[1] TRUE

In [85]:
x > y

[1] TRUE

In [86]:
x < y

[1] FALSE

In [87]:
x >= y

[1] TRUE

In [88]:
x <= y

[1] FALSE

In [89]:
fruits

[1] "Mango"    "Guava"    "Cashew"   "Agbalumo"

In [12]:
'Mango' %in% fruits

[1] TRUE

In [91]:
'Paw paw' %in% fruits

[1] FALSE

In [92]:
T

[1] TRUE

In [93]:
F

[1] FALSE

In [ ]:
#Negation with the exclamation point ! so !T becomes NOT TRUE ie FALSE
!T

[1] FALSE

In [96]:
# This means NOT FALSE ie TRUE
!F

[1] TRUE

In [97]:
# Logical operators
# & (ampersand) - means and, | (pipe) means or

T & T

[1] TRUE

In [98]:
T & F

[1] FALSE

In [99]:
F & F

[1] FALSE

In [100]:
T | T

[1] TRUE

In [101]:
T | F

[1] TRUE

In [102]:
F | F 

[1] FALSE

In [18]:
# Special symbols
# $ for accesing members of a list
# : for range of numbers
# tidyverse operators %>% or |>, `` for names of variables that contain spaces

In [15]:
# Operator precedence
# PEMDAS AKA BODMAS
# Parenthesis > Exponents > Multiplication and Division > Addition and Subtraction

In [16]:
8 / (3 + 2)

[1] 1.6

In [17]:
8 / 3 + 2

[1] 4.666667

In [5]:
# Mathematical operators and vectors

vec1 <- c(1, 2, 3, 4)
vec2 <- c(5, 4, 1, 8)

In [20]:
vec1 + 4

[1] 5 6 7 8

In [21]:
vec1  / 2

[1] 0.5 1.0 1.5 2.0

In [22]:
vec1 + vec2

[1]  6  6  4 12

In [23]:
vec1 == 4

[1] FALSE FALSE FALSE  TRUE

In [25]:
sum(as.numeric(vec1 == 4))

[1] 1

In [29]:
sum(vec1 %% 2)

[1] 2

In [31]:
vec1 %% 2 == 1

[1]  TRUE FALSE  TRUE FALSE

In [32]:
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [35]:
sum(as.numeric(scores > 95))

[1] 3

In [37]:
sum(scores >= 95)

[1] 3

In [6]:
details = list(name='Lara', location='UK', children=c('Taiwo', 'Kehinde'), childrens_ages=c(3,3), knows_data=T)

In [40]:
details

$name
[1] "Lara"

$location
[1] "UK"

$children
[1] "Taiwo"   "Kehinde"

$childrens_ages
[1] 3 3

$knows_data
[1] TRUE


In [ ]:
# the $ operatoe allows access to items in a list
details$name

[1] "Lara"

In [42]:
details$children

[1] "Taiwo"   "Kehinde"

In [44]:
details$childrens_ages

[1] 3 3

In [45]:
details$knows_data

[1] TRUE

In [46]:
#the : range operator
c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

 [1]  1  2  3  4  5  6  7  8  9 10

In [47]:
1:10

 [1]  1  2  3  4  5  6  7  8  9 10

In [48]:
1:100

  [1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30
 [31]  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
 [61]  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

In [50]:
1:1000

   [1]    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17   18   19   20   21   22   23
  [24]   24   25   26   27   28   29   30   31   32   33   34   35   36   37   38   39   40   41   42   43   44   45   46
  [47]   47   48   49   50   51   52   53   54   55   56   57   58   59   60   61   62   63   64   65   66   67   68   69
  [70]   70   71   72   73   74   75   76   77   78   79   80   81   82   83   84   85   86   87   88   89   90   91   92
  [93]   93   94   95   96   97   98   99  100  101  102  103  104  105  106  107  108  109  110  111  112  113  114  115
 [116]  116  117  118  119  120  121  122  123  124  125  126  127  128  129  130  131  132  133  134  135  136  137  138
 [139]  139  140  141  142  143  144  145  146  147  148  149  150  151  152  153  154  155  156  157  158  159  160  161
 [162]  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  178  179  180  181  182  183  184
 [185]  185  186  187  1

In [51]:
2:7

[1] 2 3 4 5 6 7

In [52]:
-4:6

 [1] -4 -3 -2 -1  0  1  2  3  4  5  6

In [53]:
4:-1

[1]  4  3  2  1  0 -1

In [54]:
1:20

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [58]:
#the seq funcgtion has more options than just in sequence and provides steps- seq(start, stop, skip)
seq(1, 10, 2)

[1] 1 3 5 7 9

In [62]:
seq(0, 1000, 9)

  [1]   0   9  18  27  36  45  54  63  72  81  90  99 108 117 126 135 144 153 162 171 180 189 198 207 216 225 234 243 252 261
 [31] 270 279 288 297 306 315 324 333 342 351 360 369 378 387 396 405 414 423 432 441 450 459 468 477 486 495 504 513 522 531
 [61] 540 549 558 567 576 585 594 603 612 621 630 639 648 657 666 675 684 693 702 711 720 729 738 747 756 765 774 783 792 801
 [91] 810 819 828 837 846 855 864 873 882 891 900 909 918 927 936 945 954 963 972 981 990 999

In [67]:
#indexing and slicing
#indexing 
#anything with one or more dimensions can be indexed

#vectors
print(scores[3])



[1] 93


In [68]:
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [70]:
scores[12]

[1] 90

In [71]:
length(scores)

[1] 12

In [ ]:
#last score
scores[length(scores)]

[1] 91

In [74]:
#second to last score
scores[length(scores) - 1]

[1] 91

In [75]:
fruits

[1] "Mango"    "Guava"    "Cashew"   "Agbalumo"

In [76]:
fruits[2]

[1] "Guava"

In [7]:
#matrix indexing
mat1 <- matrix(1:24, nrow=4)

In [81]:
mat1

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    5    9   13   17   21
[2,]    2    6   10   14   18   22
[3,]    3    7   11   15   19   23
[4,]    4    8   12   16   20   24

In [82]:
mat1[2,4]

[1] 14

In [83]:
mat1[4,4]

[1] 16

In [84]:
#indexing lists we use the $ as already shown
details$children

[1] "Taiwo"   "Kehinde"

In [86]:
details$children[1]

[1] "Taiwo"

In [88]:
#slicing
# vectors
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [89]:
scores[c(1,2,3)]

[1] 98 82 93

In [90]:
scores[c(4,5,6,7,8,9)]

[1] 97 91 94 94 96 92

In [91]:
scores[1:3]

[1] 98 82 93

In [92]:
scores[4:9]

[1] 97 91 94 94 96 92

In [93]:
scores[20]

[1] NA

In [94]:
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [96]:
scores[c(T, T, T, F, F, F, F, F, F, F, F, F)]

[1] 98 82 93

In [99]:
scores[c(F, F, F, T, T, T, T, T, T, F, F, F)]

[1] 97 91 94 94 96 92

In [100]:
scores > 95

 [1]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE

In [101]:
scores[scores > 95]

[1] 98 97 96

In [102]:
scores[scores < 90]

[1] 82

In [103]:
#how many people scors > 95
scores > 95

 [1]  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE

In [104]:
scores[scores > 95]

[1] 98 97 96

In [105]:
length(scores[scores > 95])

[1] 3

In [106]:
scores[1:3]

[1] 98 82 93

In [107]:
scores %% 2 == 1

 [1] FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE

In [ ]:
#odd numbeer scores
scores[scores %% 2 == 1]

[1] 93 97 91 91 91

In [11]:
scores

 [1] 98 82 93 97 91 94 94 96 92 91 91 90

In [17]:
#every other score
scores[seq(1, length(scores), 2)]

[1] 98 93 91 94 92 91

In [18]:
#ordering 
scores[order(scores)]

 [1] 82 90 91 91 91 92 93 94 94 96 97 98

In [22]:
#order in reverse
scores[order(scores, decreasing = T)]

 [1] 98 97 96 94 94 93 92 91 91 91 90 82

In [ ]:
#the ? operator lets you access help files. And R has awesome documentation built in
?order

In [23]:
#slicing matrices

mat1

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    5    9   13   17   21
[2,]    2    6   10   14   18   22
[3,]    3    7   11   15   19   23
[4,]    4    8   12   16   20   24

In [24]:
#row 1 only. dont specify coliumns!
mat1[1,]

[1]  1  5  9 13 17 21

In [25]:
mat1[3,]

[1]  3  7 11 15 19 23

In [26]:
#column slicing is exact opposits
mat1[,4]

[1] 13 14 15 16

In [ ]:
#slicing squares
mat1[2:4, 4:6]

     [,1] [,2] [,3]
[1,]   14   18   22
[2,]   15   19   23
[3,]   16   20   24

In [28]:
mat1[1:2,2:3]

     [,1] [,2]
[1,]    5    9
[2,]    6   10

In [ ]:
# Control structure -> logic ie if and else, loops ie for loops